FROM python:3.11-alpine

# Install necessary dependencies for Alpine
RUN apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    build-base

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container
COPY ./requirements.txt /usr/src/app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the Django app code to the container
COPY . /usr/src/app

# Expose the port Django will run on
EXPOSE 8000

# Set the default command to run Django's development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
