events {}
http {
    upstream django_backend {
        server backend:8000;
    }

    upstream react_frontend {
        server frontend:3143;
    }

    server {
        listen 80;
        location / {
                proxy_pass http://react_frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
        }
        location /static/ {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

            
    }
}
